apiVersion: v1
kind: Service
metadata:
  name: sample-flask
  namespace: default
spec:
  selector:
    app: sample-flask  
  ports:
    - protocol: TCP
      port: 80         
      targetPort: 5000
  type: LoadBalancer